pipeline {
    agent any

    environment {
        AWS_REGION = "ap-southeast-1"
        ACCOUNT_ID = "379113716280"

        ECR_REPO = "ecs-frontend"

        IMAGE_TAG = "${BUILD_NUMBER}"

        IMAGE_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"

        ECS_CLUSTER = "frontend-cluster"

        ECS_SERVICE = "ecs-frontend-service"

        TASK_FAMILY = "ecs-frontend-task"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/PrathapDev03/Login-Pages-Templates.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ECS-Template') {
                    sh 'docker build -t $ECR_REPO:$IMAGE_TAG .'
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS \
                --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag Image') {
            steps {
                sh 'docker tag $ECR_REPO:$IMAGE_TAG $IMAGE_URI'
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh 'docker push $IMAGE_URI'
            }
        }

        stage('Update ECS Task Definition') {
            steps {
                dir('ECS-Template') {
                    sh '''
                    sed -i "s|IMAGE_URI|$IMAGE_URI|g" task-definition.json
                    '''
                }
            }
        }

        stage('Register Task Definition') {
            steps {
                dir('ECS-Template') {
                    sh '''
                    aws ecs register-task-definition \
                    --cli-input-json file://task-definition.json
                    '''
                }
            }
        }

        stage('Deploy to ECS Service') {
            steps {
                sh '''
                aws ecs update-service \
                --cluster $ECS_CLUSTER \
                --service $ECS_SERVICE \
                --force-new-deployment
                '''
            }
        }
    }
}