pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/yourusername/Login-Pages.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t login-page .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker stop login-container || true
                docker rm login-container || true
                docker run -d -p 80:80 --name login-container login-page
                '''
            }
        }
    }
}