pipeline {
    agent any

    environment {
        AWS_REGION = "ap-southeast-1"

        S3_BUCKET = "frontend-cloudfront-bucket"

        DISTRIBUTION_ID = "E2STX8OC8VNNS"
    }

    stages {

        stage('Upload Files To S3') {
            steps {
                dir('CloudFront + S3 - Template') {

                    sh '''
                    /snap/bin/aws s3 sync . s3://$S3_BUCKET --delete
                    '''
                }
            }
        }

        stage('Invalidate CloudFront Cache') {
            steps {

                sh '''
                /snap/bin/aws cloudfront create-invalidation \
                --distribution-id $DISTRIBUTION_ID \
                --paths "/*"
                '''
            } 
        }
    }
}