pipeline {
    agent any

    environment {
        AWS_REGION = "ap-southeast-1"
        ECR_REPO = "ebs-frontend"
        ACCOUNT_ID = "379113716280"
        IMAGE_TAG = "latest"
        IMAGE_URI = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/PrathapDev03/Login-Pages-Templates.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Elastic Beanstalk - Template') {
                    sh 'docker build -t $ECR_REPO .'
                }
            }
        }

        stage('Login to AWS ECR') {
            steps {
                sh '''
                /snap/bin/aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS \
                --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag Docker Image') {
            steps {
                sh 'docker tag $ECR_REPO:latest $IMAGE_URI'
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh 'docker push $IMAGE_URI'
            }
        }

        stage('Deploy to Elastic Beanstalk') {
            steps {
                dir('Elastic Beanstalk - Template') {
                    sh 'zip -r deploy.zip .'
                    sh '/home/ubuntu/.local/bin/eb deploy'
                }
            }
        }
    }
}