pipeline {
    agent any

    environment {
        FUNCTION_NAME = "lambda-frontend"
        AWS_REGION = "ap-southeast-1"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/PrathapDev03/Login-Pages-Templates.git'
            }
        }

        stage('Create ZIP Package') {
            steps {
                dir('Lambda-Template') {
                    sh '''
                    zip -r lambda.zip .
                    '''
                }
            }
        }

        stage('Deploy To Lambda') {
            steps {
                dir('Lambda-Template') {
                    sh '''
                    aws lambda update-function-code \
                    --function-name $FUNCTION_NAME \
                    --zip-file fileb://lambda.zip \
                    --region $AWS_REGION
                    '''
                }
            }
        }
    }
}