pipeline {
    agent any

    environment {
        IMAGE_NAME = "cyberpunk-login-page"
        CONTAINER_NAME = "cyberpunk-login-container"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/yourusername/Login-Pages.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Stop Existing Container') {
            steps {
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker run -d -p 80:80 \
                --name $CONTAINER_NAME \
                $IMAGE_NAME
                '''
            }
        }
    }
}