pipeline {
    agent any

    environment {
        IMAGE_NAME = "login-app"
        CONTAINER_NAME = "login-container"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/PrathapDev03/Login-pages.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker run -d \
                --name $CONTAINER_NAME \
                -p 8081:80 \
                $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo 'Application Deployed Successfully!'
        }

        failure {
            echo 'Deployment Failed!'
        }
    }
}