pipeline {
    agent any

    environment {
        IMAGE_NAME = "ec2-frontend"
        CONTAINER_NAME = "ec2-container"
    }

    stages {

        stage('Clone') {
            steps {
                git branch: 'main',
                url: 'https://github.com/PrathapDev03/Login-Pages-Templates.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('EC2-Template') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f $CONTAINER_NAME || true'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker run -d \
                --name $CONTAINER_NAME \
                -p 8081:80 \
                $IMAGE_NAME
                '''
            }
        }
    }
}